### ISSUE TITLE
Tests are not functioning correctly

### ISSUE THREAD

**Issue by overlookmotel** [Boshen/criterion2.rs#50]
I noticed while working on #49 that the tests seem not to be functioning correctly. Test failures do not result in `cargo test` failing.

It appears to be related to the `#[should_panic]` tests. If you comment out the last 2 `#[should_panic]` tests, then other tests which should fail do correctly show as failing. When the `#[should_panic]` tests are enabled, it appears from output in terminal that test execution stops early. Very weird!

Please see repro case #51.

**Comment by Boshen** [comment]
Weird rust issue 🤸‍♂️ https://github.com/Boshen/criterion2.rs/commit/fb254e40d87b800fd0893adb729bf92541bd6c4f
